plugins {
	id 'java'
	id 'idea'
	id 'com.google.protobuf' version '0.9.4'
}

group = 'com.pada.sandox'
version = '1.0-SNAPSHOT'
sourceCompatibility = '21'

repositories {
	mavenCentral()
}

ext {
	grpcVersion = '1.64.0'
	protobufVersion = '3.25.1'
}

dependencies {
	implementation "io.grpc:grpc-netty-shaded:$grpcVersion"
	implementation "io.grpc:grpc-protobuf:$grpcVersion"
	implementation "io.grpc:grpc-stub:$grpcVersion"
	compileOnly "org.apache.tomcat:annotations-api:6.0.53"
    implementation("net.devh:grpc-server-spring-boot-starter:3.1.0.RELEASE")
	testImplementation 'junit:junit:4.13.2'
}

protobuf {
	protoc {
		artifact = "com.google.protobuf:protoc:$protobufVersion"
	}
	plugins {
		grpc {
			artifact = "io.grpc:protoc-gen-grpc-java:$grpcVersion"
		}
	}
	generateProtoTasks {
		all().each { task ->
			task.plugins {
				grpc {}
			}
		}
	}
}

sourceSets {
	main {
		java {
			srcDirs += ["build/generated/source/proto/main/java",
						"build/generated/source/proto/main/grpc"]
		}
	}
}
